name: Preprocess Dataset

on:
  push:
    paths:
      - 'preprocessing/automate_Jeselyn.py'
      - 'namadataset_raw/**'
      - '.github/workflows/preprocessing.yml'

jobs:
  run-preprocessing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn numpy

      - name: Run automate script
        run: python preprocessing/automate_Jeselyn.py
            - name: Upload preprocessed data
        uses: actions/upload-artifact@v3
        with:
          name: preprocessed_csv
          path: preprocessing/healthcare_preprocessed.csv

